# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-03 02:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
