# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-03 02:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0002_auto_20170603_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='fecha',
            field=models.DateField(),
        ),
    ]
