# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-03 02:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0003_auto_20170603_0206'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='comentario',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
