# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-03 02:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0004_activity_comentario'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivitySanitario',
            fields=[
                ('activity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='actividades.Activity')),
                ('cantidad', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Registros Sanitarios',
                'verbose_name': 'Registro Sanitario',
            },
            bases=('actividades.activity',),
        ),
    ]
