# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-04 05:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0005_activitysanitario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='activitym',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='activitymovement',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='activitymovement',
            name='stock_destino',
        ),
        migrations.RemoveField(
            model_name='activitysanitario',
            name='cantidad',
        ),
    ]
