# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-04 05:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0006_auto_20170604_0544'),
        ('rodeos', '0003_auto_20170604_0544'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='animal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rodeos.Animal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activitymovement',
            name='rodeo_destino',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rodeo_destino', to='rodeos.Rodeo'),
            preserve_default=False,
        ),
    ]
