# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 07:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Campo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Potrero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rodeos.Campo')),
            ],
        ),
        migrations.CreateModel(
            name='Rodeo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cantidad', models.IntegerField()),
                ('potrero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rodeos.Potrero')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal', models.CharField(choices=[('VV', 'VACA VIENTRE'), ('VE', 'VACA ENGORDE'), ('VQ', 'VAQUILLONA'), ('TO', 'TERNERO'), ('TA', 'TERNERA'), ('NT', 'NOVILLITO'), ('NO', 'NOVILLO'), ('TO', 'TORO')], max_length=2)),
                ('cantidad', models.IntegerField()),
                ('rodeo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rodeos.Rodeo')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityM',
            fields=[
                ('activity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rodeos.Activity')),
                ('cantidad', models.IntegerField()),
            ],
            bases=('rodeos.activity',),
        ),
        migrations.CreateModel(
            name='ActivityMovement',
            fields=[
                ('activity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rodeos.Activity')),
                ('cantidad', models.IntegerField()),
                ('stock_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_destino', to='rodeos.Stock')),
            ],
            bases=('rodeos.activity',),
        ),
        migrations.AddField(
            model_name='activity',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rodeos.Stock'),
        ),
    ]
