# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-01 02:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rodeo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cantidad', models.IntegerField()),
                ('potrero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campos.Potrero')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal', models.CharField(choices=[('VV', 'VACA VIENTRE'), ('VE', 'VACA ENGORDE'), ('VQ', 'VAQUILLONA'), ('TO', 'TERNERO'), ('TA', 'TERNERA'), ('NT', 'NOVILLITO'), ('NO', 'NOVILLO'), ('TO', 'TORO')], max_length=2)),
                ('cantidad', models.IntegerField()),
                ('rodeo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rodeos.Rodeo')),
            ],
            options={
                'verbose_name': 'Animal',
                'verbose_name_plural': 'Animales',
            },
        ),
    ]
