# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-04 05:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0006_auto_20170604_0544'),
        ('rodeos', '0002_auto_20170603_0205'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('VV', 'VACA VIENTRE'), ('VE', 'VACA ENGORDE'), ('Q', 'VAQUILLONA'), ('TR', 'TERNERO'), ('TA', 'TERNERA'), ('NT', 'NOVILLITO'), ('NO', 'NOVILLO'), ('TO', 'TORO')], max_length=2)),
            ],
            options={
                'verbose_name_plural': 'Animales',
                'verbose_name': 'Animal',
            },
        ),
        migrations.RemoveField(
            model_name='stock',
            name='rodeo',
        ),
        migrations.RemoveField(
            model_name='rodeo',
            name='cantidad',
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
        migrations.AddField(
            model_name='animal',
            name='rodeo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rodeos.Rodeo'),
        ),
    ]
