# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-04 06:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rodeos', '0003_auto_20170604_0544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='rodeo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rodeos.Rodeo'),
        ),
    ]
