# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-04 06:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rodeos', '0004_auto_20170604_0607'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='fecha_muerte',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='rodeo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rodeos.Rodeo'),
            preserve_default=False,
        ),
    ]
