# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-04 22:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rodeos', '0005_auto_20170604_0617'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='unidad_nutricional',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
