# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-07 02:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rodeos', '0006_animal_unidad_nutricional'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalCategoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('unidad_nutricional', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'Categorías de Animales',
                'verbose_name': 'Categoría de Animal',
            },
        ),
        migrations.RemoveField(
            model_name='animal',
            name='nombre',
        ),
        migrations.AlterField(
            model_name='animal',
            name='unidad_nutricional',
            field=models.FloatField(),
        ),
    ]
