# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-07 02:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rodeos', '0007_auto_20170607_0219'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rodeos.AnimalCategoria'),
            preserve_default=False,
        ),
    ]
